feat: Perfiles de usuario y vehículo
ISPP-AparkApp/aparkapp pull request #22
Opened 2022-03-15 23:01 UTC by JoseCarlosMorales

Se han creado los endpoints para la obtención de un vehículo dada su id, además de la edición y borrado de dicho vehículo.
Respecto a los perfiles se he realizado el endpoint de edición del mismo.

2022-03-15 23:08 UTC, JoseCarlosMorales commented
- **GET:** /api/vehicles/get/<int:pk>/
Se obtiene un vehículo dado su id. Necesita autenticación, se debe meter el token en las cabeceras: Authorization Bearer XXX
![getvehiculo](https://user-images.githubusercontent.com/72498908/158486499-d438b9f7-4d77-4582-85c2-98755c39131a.png)

- **PUT:** /api/vehicles/update/<int:pk>/
Se edita un vehículo dado su id. Necesita autenticación, se debe meter el token en las cabeceras: Authorization Bearer XXX
![updatevehiculo](https://user-images.githubusercontent.com/72498908/158486636-2bc3a366-65db-432e-867b-f2dd3ba3ff52.png)

- **DELETE:** /api/vehicles/delete/<int:pk>/
Se elimina un vehículo dado su id. Necesita autenticación, se debe meter el token en las cabeceras: Authorization Bearer XXX
![deletevehi](https://user-images.githubusercontent.com/72498908/158486743-bd08a176-3de3-4cba-9efe-078792d22a06.png)

- **PUT:** /api/user/<int:pk>//
Se edita el perfil de un usuario dado su id. Necesita autenticación, se debe meter el token en las cabeceras: Authorization Bearer XXX
![putprofile](https://user-images.githubusercontent.com/72498908/158486850-41823654-576c-47c4-ba48-16097d02f672.png)

2022-03-16 09:46 UTC, eveyugyug requested changes
- Actualizar la rama con la rama develop
- La PR debe realizarse a **develop**
- Usar **buenas prácticas** para los endpoints:
        - No usar palabras como 'get', 'delete', 'update' o 'create'
        - **Reutilizar el endpoint** /users/XXX en lugar de crear uno nuevo: /user/XX. 
        - Recoger la id del usuario en el código: /user/id/. **No se debe pasar la id del usuario en la URL.** 
        - La PR debe **prescindir** del tipo de la rama: **eliminar palabra 'feat' de la PR.**

2022-03-20 15:13 UTC, eveyugyug requested changes
**No** se deben las migraciones, borrarlas de la rama.

2022-03-22 11:57 UTC, alejandropiuryp requested changes
### Errores
- No va ningún endpoint de: Profile y de vehículo.
### Cambios
- Hay endpoints duplicados.
- Quitar operaciones a nivel global. Ej: PUT o DELETE a todos los vehículos sin ID específica.
![image](https://user-images.githubusercontent.com/30178800/159476539-ea77671f-ac4a-4b69-b9db-54fa5e89dbb9.png)

2022-03-22 20:24 UTC, merged